spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  application:
    name: "Ecommerce-Alimentacion"

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  config:
    import: optional:file:.env[.properties]

logging:
  level:
    com.example.Crud: DEBUG

security:
  jwt:
    expiration-minutes: 1
    secret-key: ZXN0YSBlcyBtaSBjbGF2ZSBkZSBhY2NjZXNvIGluIGhhY2tlYWJsZSBsb2NvIG5vIGhheSBtYW5lcmE=
